apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ndc-platform
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "api.ndc-platform.example"
  MONGO_DB_NAME: "ndc_platform"
  CORS_ALLOWED_ORIGINS: "https://ndc-platform.example"
  JWT_ACCESS_TOKEN_TTL_MINUTES: "30"
  JWT_REFRESH_TOKEN_TTL_DAYS: "7"
